#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

OUT_FILE="${OUT_FILE:-.env}"
SOURCE_ENV="${SOURCE_ENV:-SpeakCV/.env}"

read_env() {
  local file="$1"
  local key="$2"

  [[ -f "$file" ]] || return 0

  awk -F= -v key="$key" '
    $0 ~ /^[[:space:]]*#/ { next }
    $1 == key {
      sub(/^[^=]*=/, "")
      gsub(/^["'\'']|["'\'']$/, "")
      print
      exit
    }
  ' "$file"
}

is_placeholder() {
  local value="${1:-}"

  [[ -z "$value" ]] && return 0
  [[ "$value" == "auto" ]] && return 0
  [[ "$value" == "example.com" ]] && return 0
  [[ "$value" == *".example.com" ]] && return 0
  [[ "$value" == *change-this* ]] && return 0
  [[ "$value" == *your-* ]] && return 0
  [[ "$value" == *sk-your-* ]] && return 0
  [[ "$value" == *gsk_your-* ]] && return 0
  [[ "$value" == "YOUR_GOOGLE_CLIENT_ID" ]] && return 0

  return 1
}

first_real() {
  local value

  for value in "$@"; do
    if ! is_placeholder "$value"; then
      printf '%s\n' "$value"
      return 0
    fi
  done

  return 0
}

random_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    LC_ALL=C tr -dc 'a-f0-9' </dev/urandom | head -c 64
    printf '\n'
  fi
}

percent_decode() {
  local data="${1//+/ }"
  printf '%b' "${data//%/\\x}"
}

url_encode() {
  local raw="$1"
  local encoded=""
  local i char hex

  for ((i = 0; i < ${#raw}; i++)); do
    char="${raw:i:1}"
    case "$char" in
      [a-zA-Z0-9.~_-]) encoded+="$char" ;;
      *) printf -v hex '%%%02X' "'$char"; encoded+="$hex" ;;
    esac
  done

  printf '%s\n' "$encoded"
}

extract_db_password() {
  local url="$1"
  local password=""

  if [[ "$url" =~ ^[^:]+://[^:]+:([^@]+)@ ]]; then
    password="${BASH_REMATCH[1]}"
    percent_decode "$password"
  fi
}

base_value() {
  read_env "$OUT_FILE" "$1"
}

source_value() {
  read_env "$SOURCE_ENV" "$1"
}

existing_db_url="$(first_real "$(base_value DATABASE_URL)" "$(source_value DATABASE_URL)")"
existing_db_password="$(extract_db_password "$existing_db_url")"

public_host="$(first_real "$(base_value PUBLIC_HOST)")"
enable_proxy="$(first_real "$(base_value ENABLE_PROXY)")"
mysql_database="$(first_real "$(base_value MYSQL_DATABASE)" "speakcv")"
mysql_root_password="$(first_real "$(base_value MYSQL_ROOT_PASSWORD)" "$existing_db_password")"
secret_key="$(first_real "$(base_value SECRET_KEY)")"
admin_email="$(first_real "$(source_value ADMIN_EMAIL)" "$(base_value ADMIN_EMAIL)" "admin@gmail.com")"
admin_password="$(first_real "$(source_value ADMIN_PASSWORD)" "$(base_value ADMIN_PASSWORD)")"
admin_name="$(first_real "$(source_value ADMIN_NAME)" "$(base_value ADMIN_NAME)" "Admin")"
access_token_minutes="$(first_real "$(base_value ACCESS_TOKEN_EXPIRE_MINUTES)" "3000")"
jwt_algorithm="$(first_real "$(base_value JWT_ALGORITHM)" "HS256")"

if is_placeholder "$public_host"; then
  public_host="auto"
fi

if is_placeholder "$enable_proxy"; then
  enable_proxy="0"
fi

if is_placeholder "$mysql_root_password"; then
  mysql_root_password="$(random_hex)"
fi

if is_placeholder "$secret_key"; then
  secret_key="$(random_hex)"
fi

if is_placeholder "$admin_password"; then
  admin_password="$(random_hex)"
fi

encoded_mysql_password="$(url_encode "$mysql_root_password")"
database_url="mysql+pymysql://root:${encoded_mysql_password}@db:3306/${mysql_database}"

google_client_id="$(first_real "$(source_value NEXT_PUBLIC_GOOGLE_CLIENT_ID)" "$(base_value NEXT_PUBLIC_GOOGLE_CLIENT_ID)")"
gemini_api_key="$(first_real "$(source_value GEMINI_API_KEY)" "$(base_value GEMINI_API_KEY)")"
openai_api_key="$(first_real "$(source_value OPENAI_API_KEY)" "$(base_value OPENAI_API_KEY)")"
openai_base_url="$(first_real "$(source_value OPENAI_BASE_URL)" "$(base_value OPENAI_BASE_URL)" "https://api.openai.com/v1")"
groq_api_key="$(first_real "$(source_value GROQ_API_KEY)" "$(base_value GROQ_API_KEY)")"
openai_model_mini="$(first_real "$(source_value OPENAI_MODEL_GPT4O_MINI)" "$(base_value OPENAI_MODEL_GPT4O_MINI)" "gpt-4.1-mini")"
openai_model_full="$(first_real "$(source_value OPENAI_MODEL_GPT4O)" "$(base_value OPENAI_MODEL_GPT4O)" "gpt-4.1")"

primary_domain="$(first_real "$(base_value PRIMARY_DOMAIN)")"
speakcv_domain="$(first_real "$(base_value SPEAKCV_DOMAIN)")"
api_domain="$(first_real "$(base_value API_DOMAIN)")"

if is_placeholder "$primary_domain"; then primary_domain=""; fi
if is_placeholder "$speakcv_domain"; then speakcv_domain=""; fi
if is_placeholder "$api_domain"; then api_domain=""; fi

tmp_file="$(mktemp)"
cat >"$tmp_file" <<EOF
# Generated by scripts/sync-vps-env.sh.
# Do not print this file in logs; it contains production secrets.

# VPS mode
ENABLE_PROXY=${enable_proxy}
PUBLIC_HOST=${public_host}
INTERVIEWPATH_PORT=$(first_real "$(base_value INTERVIEWPATH_PORT)" "5173")
SPEAKCV_FRONTEND_PORT=$(first_real "$(base_value SPEAKCV_FRONTEND_PORT)" "3000")
SPEAKCV_BACKEND_PORT=$(first_real "$(base_value SPEAKCV_BACKEND_PORT)" "8000")

# Optional HTTPS/domain proxy mode. Set ENABLE_PROXY=1 and fill these.
PRIMARY_DOMAIN=${primary_domain}
SPEAKCV_DOMAIN=${speakcv_domain}
API_DOMAIN=${api_domain}

# Public URLs. scripts/vps-deploy.sh resolves these from PUBLIC_HOST on the VPS.
VITE_SPEAKCV_URL=http://localhost:3000
NEXT_PUBLIC_API_URL=http://localhost:8000
NEXT_PUBLIC_GOOGLE_CLIENT_ID=${google_client_id}
CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173
VNPAY_RETURN_URL=http://localhost:3000/upgrade/success

# Database
MYSQL_DATABASE=${mysql_database}
MYSQL_ROOT_PASSWORD=${mysql_root_password}
DATABASE_URL=${database_url}

# Auth/admin
SECRET_KEY=${secret_key}
JWT_ALGORITHM=${jwt_algorithm}
ACCESS_TOKEN_EXPIRE_MINUTES=${access_token_minutes}
ADMIN_EMAIL=${admin_email}
ADMIN_PASSWORD=${admin_password}
ADMIN_NAME=${admin_name}

# AI providers
GEMINI_API_KEY=${gemini_api_key}
OPENAI_API_KEY=${openai_api_key}
OPENAI_BASE_URL=${openai_base_url}
OPENAI_MODEL_GPT4O_MINI=${openai_model_mini}
OPENAI_MODEL_GPT4O=${openai_model_full}
GROQ_API_KEY=${groq_api_key}

# AI runtime tuning
AI_MAX_HISTORY_MESSAGES=$(first_real "$(source_value AI_MAX_HISTORY_MESSAGES)" "$(base_value AI_MAX_HISTORY_MESSAGES)" "16")
AI_TOKEN_CHAR_BUDGET=$(first_real "$(source_value AI_TOKEN_CHAR_BUDGET)" "$(base_value AI_TOKEN_CHAR_BUDGET)" "18000")
AI_DEFAULT_MAX_OUTPUT_TOKENS=$(first_real "$(source_value AI_DEFAULT_MAX_OUTPUT_TOKENS)" "$(base_value AI_DEFAULT_MAX_OUTPUT_TOKENS)" "500")
AI_ENABLE_CACHE=$(first_real "$(source_value AI_ENABLE_CACHE)" "$(base_value AI_ENABLE_CACHE)" "1")
AI_CACHE_TTL_SECONDS=$(first_real "$(source_value AI_CACHE_TTL_SECONDS)" "$(base_value AI_CACHE_TTL_SECONDS)" "300")
AI_ROUTER_CHAR_THRESHOLD=$(first_real "$(source_value AI_ROUTER_CHAR_THRESHOLD)" "$(base_value AI_ROUTER_CHAR_THRESHOLD)" "850")
AI_ENABLE_BRAIN_RETRIEVAL=$(first_real "$(source_value AI_ENABLE_BRAIN_RETRIEVAL)" "$(base_value AI_ENABLE_BRAIN_RETRIEVAL)" "1")
AI_BRAIN_RETRIEVAL_DEBUG=$(first_real "$(source_value AI_BRAIN_RETRIEVAL_DEBUG)" "$(base_value AI_BRAIN_RETRIEVAL_DEBUG)" "0")
AI_BRAIN_CONTEXT_MAX_CHARS=$(first_real "$(source_value AI_BRAIN_CONTEXT_MAX_CHARS)" "$(base_value AI_BRAIN_CONTEXT_MAX_CHARS)" "3200")
AI_USAGE_LOG_FILE=$(first_real "$(source_value AI_USAGE_LOG_FILE)" "$(base_value AI_USAGE_LOG_FILE)" "/tmp/speakcv-backend.log")

# VNPAY optional settings
VNPAY_TMN_CODE=$(first_real "$(source_value VNPAY_TMN_CODE)" "$(base_value VNPAY_TMN_CODE)")
VNPAY_HASH_SECRET=$(first_real "$(source_value VNPAY_HASH_SECRET)" "$(base_value VNPAY_HASH_SECRET)")
VNPAY_PAYMENT_URL=$(first_real "$(source_value VNPAY_PAYMENT_URL)" "$(base_value VNPAY_PAYMENT_URL)" "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html")
EOF

chmod 600 "$tmp_file"
mv "$tmp_file" "$OUT_FILE"

echo "Wrote $OUT_FILE with root-level VPS env keys."
echo "Copied provider/build keys from $SOURCE_ENV when real values were present."
