# Copyright (c) 2026 SpeakCV Team
# This project is licensed under the MIT License.
# See the LICENSE file in the project root for more information.

import os
import io
import urllib.parse
import requests
import time
import json
import re
import edge_tts
from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile, Request
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from dotenv import load_dotenv

from .. import models
from ..database import sql_models
from ..database.database import get_db
from .profile import get_current_user
from ..ai_service import call_ai_chat

# Import dynamic prompting modules
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../../'))
from core.knowledge_graph import get_next_topic
from core.nunchi_analyzer import analyze_candidate_response

load_dotenv() 

router = APIRouter()

guest_ip_tracker = {}

api_key = os.getenv("GEMINI_API_KEY") or os.getenv("OPENAI_API_KEY")


def is_english_voice(voice_id: str | None) -> bool:
    if not voice_id:
        return False
    voice = voice_id.lower()
    if voice.startswith("en-"):
        return True
    english_markers = ["english", "en-us", "en-gb", "andrew", "jenny", "aria"]
    return any(marker in voice for marker in english_markers)

def clean_and_parse_json(raw_text: str):
    """Clean garbage characters generated by AI before parsing JSON"""
    cleaned = re.sub(r'^```json\s*', '', raw_text, flags=re.IGNORECASE)
    cleaned = re.sub(r'^```\s*', '', cleaned)
    cleaned = re.sub(r'\s*```$', '', cleaned)
    
    cleaned = re.sub(r',\s*}', '}', cleaned)
    cleaned = re.sub(r',\s*]', ']', cleaned)
    
    cleaned = cleaned.strip()
    
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError as e:
        print(f"JSON Parse Error: {e}")
        print(f"Cleaned raw string: {cleaned}")
        raise ValueError("AI returned invalid JSON format.")


def _english_transcript_is_low_quality(text: str) -> bool:
    words = re.findall(r"[a-zA-Z']+", text.lower())
    if len(words) < 4:
        return True
    common_en = {
        "i", "have", "years", "year", "experience", "with", "python", "fastapi",
        "backend", "frontend", "project", "worked", "team", "api", "and", "the", "to"
    }
    hit = sum(1 for w in words if w in common_en)
    ratio = hit / max(len(words), 1)
    return ratio < 0.12

@router.post("/api/transcribe")
async def transcribe_audio(
    file: UploadFile = File(...), 
    position: str = Form("Chung"),
    lang: str = Form("vi"),
    currentQuestion: str = Form("")
):
    try:
        file_location = f"temp_{file.filename}"
        with open(file_location, "wb+") as file_object:
            file_object.write(file.file.read())

        url = "https://api.groq.com/openai/v1/audio/transcriptions"
        groq_key = os.getenv("GROQ_API_KEY") 
        if not groq_key: return {"text": "Error: GROQ_API_KEY not configured"}
            
        headers = { "Authorization": f"Bearer {groq_key}" }
        
        if lang == "en":
            dynamic_prompt = (
                f"Interview context for {position}. Transcribe clear English speech only. "
                "Keep technical terms exact: Python, FastAPI, backend, frontend, API, Docker, Redis, Kubernetes."
            )
        else:
            dynamic_prompt = f"Chào bạn, tôi đang phỏng vấn cho vị trí {position}. Tôi sẽ chia sẻ về kinh nghiệm làm việc, kỹ năng chuyên môn, quá trình học tập, quản lý dự án, doanh số và định hướng nghề nghiệp của mình."

        with open(file_location, "rb") as audio_file:
            files = { "file": (file.filename, audio_file, "audio/webm") }

        with open(file_location, "rb") as audio_file:
            files = { "file": (file.filename, audio_file, "audio/webm") }
            data = { 
                "model": "whisper-large-v3",
                "language": lang,
                "prompt": dynamic_prompt,
                "temperature": 0.0 
            }
            
            res = requests.post(url, headers=headers, files=files, data=data, timeout=30)
            
        if os.path.exists(file_location): os.remove(file_location)

        if res.status_code == 200:
            text = res.json().get("text", "").strip()
            
            bad_phrases = [
                "cảm ơn", "thank you",
                "hẹn gặp lại", "bye bye", "tạm biệt"
            ]
            
            lower_text = text.lower()
            if any(phrase in lower_text for phrase in bad_phrases) or len(text) < 2:
                return {"text": ""} 

            if lang == "en" and _english_transcript_is_low_quality(text):
                return {"text": "Please repeat that in English, I could not capture it clearly."}
            
            return {"text": text}
        else:
            return {"text": ""} 
            
    except Exception as e:
        return {"text": ""}

@router.post("/api/chat")
async def chat(request: models.ChatRequest, http_req: Request, db: Session = Depends(get_db)):
    client_ip = http_req.client.host

    user = None
    auth_header = http_req.headers.get("Authorization")
    if not auth_header or auth_header == "Bearer null":
        current_count = guest_ip_tracker.get(client_ip, 0)
        
        if current_count >= 20:
            print(f"[!] Blocked IP {client_ip} - exceeded 20 free turns.")
            raise HTTPException(status_code=429, detail="Bạn đã dùng hết 20 lượt miễn phí. Vui lòng đăng nhập!")
            
        guest_ip_tracker[client_ip] = current_count + 1
        print(f"[INFO] IP {client_ip} using turn {guest_ip_tracker[client_ip]}/20")
    else:
        token_str = auth_header.replace("Bearer ", "").strip()
        try:
            from ..auth import security
            email = security.verify_token(token_str)
            if email:
                user = db.query(sql_models.User).filter(sql_models.User.email == email).first()
                if user:
                    from app.utils import sync_user_tokens
                    sync_user_tokens(user, db)
                    
                    if user.credits < 1:
                        raise HTTPException(status_code=403, detail="Bạn đã hết số lượng token trong ngày. Vui lòng thử lại vào ngày mai hoặc nâng cấp Pro.")
        except Exception as e:
            print(f"Auth error in chat: {e}")
    
    safe_user_text = request.user_text.encode('ascii', 'ignore').decode('ascii')
    print(f"[User Msg] User: {safe_user_text} | Voice: {request.voice_id}")

    if not api_key:
        print("[CRITICAL ERROR] No AI API key found in .env (GEMINI_API_KEY or OPENAI_API_KEY)")
        raise HTTPException(status_code=500, detail="API Key not configured")

    ai_text = ""

    prompt_config = db.query(sql_models.SystemConfig).filter_by(setting_key="system_prompt").first()
    temp_config = db.query(sql_models.SystemConfig).filter_by(setting_key="temperature").first()

    requested_lang = (request.lang or "").strip().lower()
    is_english = requested_lang.startswith("en") or is_english_voice(request.voice_id)

    # === DYNAMIC PROMPTING: Analyze candidate response ===
    analysis = analyze_candidate_response(request.user_text)
    print(f"[Nunchi Analysis] Intent: {analysis['intent']}, Confidence: {analysis['confidence_level']}, Fillers: {analysis['filler_count']}")

    # === KNOWLEDGE GRAPH: Determine next topic ===
    # Extract current topic from chat history or default to foundation
    current_topic = "JavaScript Fundamentals"  # Default starting point
    candidate_passed = True  # Default assumption

    # Simple heuristic: if candidate is skipping or has low confidence, they likely didn't pass
    if analysis['intent'] == 'skipping' or analysis['confidence_level'] == 'Low Confidence / Nervous':
        candidate_passed = False

    # Get next topic from knowledge graph
    next_topic = get_next_topic(current_topic, candidate_passed)
    print(f"[Knowledge Graph] Current: {current_topic}, Passed: {candidate_passed}, Next: {next_topic}")

    # === DYNAMIC PROMPT GENERATION ===
    temperature = float(temp_config.setting_value) if temp_config else 0.7

    # === STEP 1: Get base prompt from frontend/DB ===
    # Default base prompts if not configured
    default_prompt_en = """You are a professional HR Director conducting a technical interview.
You are strict but fair, professional, and direct. Keep responses concise and ask relevant technical questions."""

    default_prompt_vi = """Bạn là Giám đốc Nhân sự chuyên nghiệp đang phỏng vấn ứng viên.
Bạn nghiêm khắc nhưng công bằng, chuyên nghiệp và trực tiếp. Trả lời ngắn gọn và hỏi câu hỏi kỹ thuật phù hợp."""

    # Get base prompt from DB config or use default
    if prompt_config and prompt_config.setting_value:
        base_prompt = prompt_config.setting_value
    else:
        base_prompt = default_prompt_en if is_english else default_prompt_vi

    # Add context about position and mode
    base_prompt += f"\n\nInterview Position: {request.jd_text}\nInterview Mode: {request.mode}"

    # Always enforce response language from current settings.
    # This prevents DB-configured system prompts (often Vietnamese) from
    # unintentionally overriding the selected AI voice/language.
    if is_english:
        base_prompt += "\n\n[LANGUAGE POLICY] You MUST respond in natural English only. Do not use Vietnamese."
    else:
        base_prompt += "\n\n[CHÍNH SÁCH NGÔN NGỮ] Bạn PHẢI trả lời bằng tiếng Việt tự nhiên. Không dùng tiếng Anh."

    # === STEP 2: Build cognitive architecture rules ===
    if is_english:
        cognitive_rules = f"""

[REAL-TIME COGNITIVE SYSTEM DIRECTIVES]
- Candidate's Intent: {analysis['intent']}
- Candidate's Confidence: {analysis['confidence_level']}
- Next Technical Topic to Evaluate: {next_topic}

[STRICT ACTIONS TO FOLLOW]
1. If Intent is 'skipping' → Move on instantly without explaining the answer. Say "Let's move on" and ask about {next_topic}.
2. If Intent is 'asking_reverse_question' → Politely decline ("We'll do Q&A at the end") and redirect to the interview.
3. If Confidence is 'Low Confidence / Nervous' → Soften your tone to encourage them. Use supportive language.
4. You MUST end your response with exactly ONE question specifically about: {next_topic}.
5. Keep your entire response extremely concise (UNDER 50 words total).
6. Use natural conversational fill-ups like "Um...", "Well...", "Interesting..." to sound human, not robotic.
"""
    else:
        cognitive_rules = f"""

[CHỈ THỊ HỆ THỐNG NHẬN THỨC THỜI GIAN THỰC]
- Ý định của ứng viên: {analysis['intent']}
- Độ tự tin: {analysis['confidence_level']}
- Chủ đề kỹ thuật tiếp theo: {next_topic}

[HÀNH ĐỘNG BẮT BUỘC]
1. Nếu Intent là 'skipping' → Chuyển ngay không giải thích. Nói "Chuyển sang câu khác" và hỏi về {next_topic}.
2. Nếu Intent là 'asking_reverse_question' → Lịch sự từ chối ("Chúng ta sẽ có phần hỏi đáp sau") và quay lại phỏng vấn.
3. Nếu Confidence là 'Low Confidence / Nervous' → Dùng giọng điệu khuyến khích, hỗ trợ.
4. Bạn PHẢI kết thúc bằng MỘT câu hỏi cụ thể về: {next_topic}.
5. Giữ câu trả lời CỰC KỲ ngắn gọn (DƯỚI 50 từ).
"""

    # === STEP 3: Concatenate base prompt + cognitive rules ===
    final_system_prompt = base_prompt + cognitive_rules

    print(f"[Dynamic Prompt] Base: {len(base_prompt)} chars, Cognitive: {len(cognitive_rules)} chars, Total: {len(final_system_prompt)} chars")
    
    messages = [{"role": "system", "content": final_system_prompt}]
    if request.chat_history:
        messages.extend(request.chat_history)
    messages.append({"role": "user", "content": request.user_text})

    for attempt in range(3):
        try:
            print(f"[*] Calling AI (attempt {attempt + 1})...")
            ai_text = call_ai_chat(
                messages=messages,
                model="gpt-4o-mini",
                temperature=temperature,
                max_tokens=250,
                timeout=90
            )
            if ai_text:
                if user:
                    user.credits -= 1
                    db.commit()
                break
            time.sleep(2)
        except Exception as e:
            print(f"[Warning] AI error (attempt {attempt+1}): {e}")
            time.sleep(2)

    ai_text = str(ai_text).strip() or "Network is unstable, please say that again."
    safe_ai_text = ai_text.encode('ascii', 'ignore').decode('ascii')
    print(f"[AI Reply] AI: {safe_ai_text}")

    try:
        voice = request.voice_id if not request.voice_id.startswith("openai-") else "en-US-AndrewMultilingualNeural"
        communicate = edge_tts.Communicate(ai_text, voice)
        audio_stream = io.BytesIO()
        async for chunk in communicate.stream():
            if chunk["type"] == "audio": audio_stream.write(chunk["data"])
        audio_stream.seek(0)
        return StreamingResponse(audio_stream, media_type="audio/mpeg", headers={"X-AI-Response-Text": urllib.parse.quote(ai_text)})
    except Exception as e:
        print(f"[Error] TTS error: {e}")
        return StreamingResponse(io.BytesIO(), media_type="audio/mpeg", headers={"X-AI-Response-Text": urllib.parse.quote("Audio error.")})

@router.post("/api/hint")
async def get_hint(request: models.HintRequest):
    try:
        messages = [{"role": "system", "content": "Gợi ý 3 ý ngắn."}, {"role": "user", "content": f"Câu hỏi: {request.last_question}. JD: {request.jd_text}"}]
        result = call_ai_chat(messages=messages, model="gpt-4o", timeout=30)
        return {"hint": result}
    except: return {"hint": "Unable to fetch hints."}

@router.post("/api/end-interview")
async def end_interview(request: models.ReportRequest, current_user: sql_models.User = Depends(get_current_user), db: Session = Depends(get_db)):
    try:
        system_prompt = f"""
        Bạn là HR. Đánh giá ứng viên vị trí: {request.jd_text}.
        DỰA CHÍNH XÁC VÀO LỊCH SỬ PHỎNG VẤN. QUY TẮC TỐI THƯỢNG:
        1. BẮT BUỘC PHẢI TRÍCH XUẤT VÀ ĐÁNH GIÁ TẤT CẢ CÁC CÂU HỎI CỦA AI CÓ TRONG LỊCH SỬ. SỐ LƯỢNG OBJECT TRONG MẢNG `details` PHẢI BẰNG ĐÚNG SỐ LƯỢNG CÂU HỎI TRONG LỊCH SỬ! TUYỆT ĐỐI KHÔNG ĐƯỢC LƯỢC BỎ BẤT KỲ CÂU NÀO.
        2. TUYỆT ĐỐI KHÔNG tự bịa ra câu trả lời của ứng viên.
        3. PHÂN BIỆT RÕ RÀNG TRẠNG THÁI TRẢ LỜI: BẠN CHỈ ĐƯỢC PHÉP ghi 'Ứng viên chưa trả lời' vào `candidate_answer` nếu trong lịch sử AI vừa hỏi mà ứng viên chưa có câu trả lời nào bên dưới, hoặc ứng viên CỐ TÌNH BỎ QUA (dùng từ 'next', 'không biết', 'bỏ qua'). Không trừ điểm câu đó nếu bị ngắt do lỗi hệ thống.
        4. NẾU ỨNG VIÊN CÓ ĐƯA RA CÂU TRẢ LỜI: Cho dù câu trả lời đó sai kiến thức, thiếu ý, lan man, hay ngô nghê, BẠN BẮT BUỘC PHẢI trích dẫn nguyên văn câu nói đó vào trường `candidate_answer`. TUYỆT ĐỐI KHÔNG ĐƯỢC gán nhãn là 'Ứng viên chưa trả lời' trong trường hợp này.
        5. Đối với các câu trả lời sai/thiếu đó, hãy chấm điểm thấp và ghi rõ lý do sai vào trường `evaluation`.
        6. Bạn sẽ trả lời bằng ngôn ngữ mà người sử dụng đang dùng để làm phỏng vấn tiếng Anh hoặc tiếng Việt tùy xem người dùng đang sử dụng ngôn ngữ nào.
        
        QUY TẮC QUAN TRỌNG VỀ LỊCH SỬ BỊ GIÁN ĐOẠN: 
        Nếu ứng viên trả lời một câu hỏi cũ đã từng bị bỏ qua hoặc bị ngắt quãng trước đó, bạn PHẢI tự động ghép nối câu trả lời mới đó vào đúng câu hỏi tương ứng. GHI ĐÈ lên trạng thái 'Ứng viên chưa trả lời'. TUYỆT ĐỐI KHÔNG tạo ra 2 bản ghi trùng lặp cho cùng 1 câu hỏi.
        
        BẮT BUỘC trả về JSON (không có markdown):
        {{
            "score": <điểm float 1-10>,
            "inferred_position": "<Dự đoán chức danh công việc dựa trên câu hỏi (dưới 5 từ). Nếu không rõ, ghi 'Tự do'>",
            "overall_feedback": "<Nhận xét tổng quan>",
            "details": [
                {{
                    "question": "<Câu AI hỏi>",
                    "candidate_answer": "<Trích dẫn ĐÚNG LỜI ứng viên>",
                    "evaluation": "<Nhận xét chi tiết>",
                    "ideal_answer": "<Câu trả lời mẫu>"
                }}
                ... (LẶP LẠI CHO TẤT CẢ CÁC CÂU HỎI TRONG LỊCH SỬ, CŨ LẪN MỚI)
            ]
        }}
        """
        
        messages = [{"role": "system", "content": system_prompt}, {"role": "user", "content": f"Lịch sử:\n{request.history}"}]
        
        raw_content = call_ai_chat(
            messages=messages,
            model="gpt-4o-mini",
            temperature=0.2,
            max_tokens=4000,
            response_format={"type": "json_object"},
            timeout=90
        )
        
        if raw_content:
            report_data = clean_and_parse_json(raw_content)
            score = report_data.get("score", 0)
            overall_feedback = report_data.get("overall_feedback", "")
            details = report_data.get("details", [])
            
            inferred_position = report_data.get("inferred_position", "").strip()
            
            final_position = request.position
            if not final_position or final_position.strip().lower() in ["", "chung", "tự do", "free", "none", "null"]:
                final_position = inferred_position if inferred_position else "Tự do"

            history_id = None
            if request.history_id is not None:
                existing = db.query(sql_models.InterviewHistory).filter(
                    sql_models.InterviewHistory.id == request.history_id,
                    sql_models.InterviewHistory.user_id == current_user.id
                ).first()
                if existing:
                    existing.score = score
                    existing.overall_feedback = overall_feedback
                    existing.details = details
                    
                    if not existing.position or existing.position.strip().lower() in ["", "chung", "tự do"]:
                        existing.position = final_position
                        existing.title = f"Phỏng vấn {final_position}"
                        
                    db.commit()
                    history_id = existing.id
            
            if history_id is None:
                title = f"Phỏng vấn {final_position}"
                new_history = sql_models.InterviewHistory(
                    user_id=current_user.id,
                    position=final_position,
                    title=title,
                    score=score,
                    overall_feedback=overall_feedback,
                    details=details,
                    interview_type=request.interview_type,
                    question_limit=request.question_limit,
                    time_limit=request.time_limit
                )
                db.add(new_history)
                db.commit()
                db.refresh(new_history)
                history_id = new_history.id
            else:
                existing.interview_type = request.interview_type
                existing.question_limit = request.question_limit
                existing.time_limit = request.time_limit
                db.commit()
            
            return {"report": report_data, "history_id": history_id}
        else:
            return {"report": {"score": 0, "overall_feedback": "AI Server error.", "details": []}}
            
    except Exception as e: 
        print(f"[Error] Report error: {e}")
        return {"report": {"score": 0, "overall_feedback": "System error.", "details": []}}

@router.get("/api/history")
async def get_interview_history(current_user: sql_models.User = Depends(get_current_user), db: Session = Depends(get_db)):
    histories = db.query(sql_models.InterviewHistory).filter(sql_models.InterviewHistory.user_id == current_user.id).order_by(sql_models.InterviewHistory.created_at.desc()).all()
    return {"histories": histories}

@router.put("/api/history/{history_id}")
async def update_interview_history(
    history_id: int, 
    request: models.RenameRequest, 
    current_user: sql_models.User = Depends(get_current_user), 
    db: Session = Depends(get_db)
):
    history = db.query(sql_models.InterviewHistory).filter(
        sql_models.InterviewHistory.id == history_id,
        sql_models.InterviewHistory.user_id == current_user.id
    ).first()
    if not history:
        raise HTTPException(status_code=404, detail="Interview history not found.")
    
    history.title = request.title
    db.commit()
    return {"message": "Updated successfully"}

@router.patch("/api/history/{history_id}/config")
async def update_interview_config(
    history_id: int,
    request: models.UpdateInterviewConfig,
    current_user: sql_models.User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    history = db.query(sql_models.InterviewHistory).filter(
        sql_models.InterviewHistory.id == history_id,
        sql_models.InterviewHistory.user_id == current_user.id
    ).first()
    if not history:
        raise HTTPException(status_code=404, detail="Interview history not found.")
    
    history.interview_type = request.interview_type
    history.question_limit = request.question_limit
    history.time_limit = request.time_limit
    db.commit()
    return {
        "message": "Config updated successfully",
        "interview_type": history.interview_type,
        "question_limit": history.question_limit,
        "time_limit": history.time_limit,
    }

@router.delete("/api/history/{history_id}")
async def delete_interview_history(
    history_id: int, 
    current_user: sql_models.User = Depends(get_current_user), 
    db: Session = Depends(get_db)
):
    history = db.query(sql_models.InterviewHistory).filter(
        sql_models.InterviewHistory.id == history_id,
        sql_models.InterviewHistory.user_id == current_user.id
    ).first()
    if not history:
        raise HTTPException(status_code=404, detail="Interview history not found.")
    
    db.delete(history)
    db.commit()
    return {"message": "Deleted successfully"}
